#!/bin/bash

intltool-extract --type=gettext/glade share/formatstick/formatstick.ui
xgettext --language=Python --keyword=_ --keyword=N_ --output=formatstick.pot lib/formatstick.py generate_additional_files.py share/formatstick/formatstick.ui.h
rm -f share/formatstick/formatstick.ui.h
